version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.3.7"

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies..."
      - pip install checkov
      - echo "Installing Terraform version ${TERRAFORM_VERSION}..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - rm terraform.zip
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
  build:
    commands:
      - echo "Validating Terraform configuration..."
      - terraform validate
      - echo "Planning Terraform deployment..."
      - terraform plan -var-file="vars/main.tfvars" -out=tfplan.binary
      - terraform show -json tfplan.binary > tfplan.json
      - echo "Running Checkov scan..."
      - checkov -f tfplan.json || echo "Checkov scan failed, but continuing..."
artifacts:
  files:
    - "**/*"
