version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - rm terraform.zip
  build:
    commands:
      - echo "Applying Terraform plan..."
      # - terraform apply -var-file="vars/main.tfvars" -auto-approve tfplan.binary
      - terraform apply --auto-approve
# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.x
#     commands:
#       - echo "Installing Terraform..."
#       - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
#       - unzip terraform.zip
#       - mv terraform /usr/local/bin/
#       - rm terraform.zip
#   pre_build:
#     commands:
#       - echo "Reinitializing Terraform..."
#       - terraform init -lockfile=readonly
#   build:
#     commands:
#       - echo "Applying Terraform plan..."
#       # - terraform apply -var-file="vars/main.tfvars" -auto-approve tfplan.binary
#       - terraform apply -auto-approve tfplan.binary
