version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.3.7"

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform version ${TERRAFORM_VERSION}..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - rm terraform.zip
  build:
    commands:
      - echo "Applying Terraform plan..."
      - terraform destroy -var-file="vars/main.tfvars" --auto-approve
